Movies
Ievgen-Mykhailiuk/Movies pull request #1
Opened 2022-10-04 07:27 UTC by Ievgen-Mykhailiuk

2022-10-07 17:09 UTC, Nikitax23 requested changes
На данный момент нужно быть внимательнее и не повторять ошибок.

2022-10-07 17:09 UTC, Nikitax23 commented on Movies/Movies/Application/SceneDelegate.swift
> +        window = UIWindow(frame: windowScene.coordinateSpace.bounds)
следует вынести в отдельный приватный метод

2022-10-07 17:09 UTC, Nikitax23 commented on Movies/Movies/Application/SceneDelegate.swift
> +        CoreDataService().saveContext()
`CoreDataService()`

таким образом ты каждый раз инитишь новый инстанс кор дата сервиса. 
надо или чтоб он был синглтоном, или чтоб он был проинициализирован однажды , где-то в одном месте, и везде использовался оттуда.

2022-10-07 17:09 UTC, Nikitax23 commented on Movies/Movies/BaseServices/BaseNetworkService.swift
> +                               httpMethod: BaseNetworkService.HttpMethod,
1) httpMethod мы должны получать из endPoint-a в текущей реализации. 
2)  `httpMethod: BaseNetworkService.HttpMethod` у Alamofire есть  уже энам HttpMethod. 
Зачем ты его дублируешь?

2022-10-07 17:09 UTC, Nikitax23 commented on Movies/Movies/BaseServices/BaseNetworkService.swift
> +    enum HttpMethod: String {
убрать этот энам

2022-10-07 17:09 UTC, Nikitax23 commented on Movies/Movies/BaseServices/BaseNetworkService.swift
> +        guard let url = endPoint.url else { return }
нужно возвращать ошибку, что URL - невалидный.

2022-10-07 17:09 UTC, Nikitax23 commented on Movies/Movies/BaseServices/Constants.swift
> +    static let smallPosterSize = CGSize(width: 230, height: 350)
зачем эти сайзы лежат видны на весь проект? тебе ведь постеры не нужны во всем проекте? или нужны?

2022-10-07 17:09 UTC, Nikitax23 commented on Movies/Movies/BaseServices/Constants.swift
> +    static let offlineMsg = "You are offline. Please enable your Wi-Fi or connect using cellular data"
`    static let offlineMsg = "You are offline. Please enable your Wi-Fi or connect using cellular data"
`

это может быть кастомной ошибкой, а не просто константой строки

2022-10-07 17:09 UTC, Nikitax23 commented on Movies/Movies/BaseServices/EndPoint.swift
> +            let sortType = URLQueryItem(name: "sort_by", value: "popularity.desc")
это всё можно сделать гораздо проще.

1) нужно сделать свойство `parameters`, в котором ты будешь собирать параметры, как словарь. (обрати внимание, что у тебя будут повторяющиеся параметры)

2) создать свойство `encoding: ParameterEncoding`. оно бывает URLEncoding, JSONEncoding. 
определяет, какого типа параметры тебе нужны: `query` или `body`

3) просто передать в аламофаер параметры и твой энкодинг. 

он таким образом сам за тебя построит правильно урл, когда ты ему отдашь полную url строку (включая baseUrl и path)

2022-10-07 17:09 UTC, Nikitax23 commented on Movies/Movies/BaseServices/EndPoint.swift
> +            return "/3/discover/movie"
здесь `3`  - это версия API. 
это можно вынести в отдельное свойство. 

дальше должен быть метод, который будет билдить твою урл строку , в зависимости от baseUrl, version, path, parameters.

2022-10-07 17:09 UTC, Nikitax23 commented on Movies/Movies/CoreData/CoreDataService.swift
> +                if movieEntity == nil && poster != nil {
странное условие. 
нужно сохранять всю сущность. не понимаю, при чем здесь условия

2022-10-07 17:09 UTC, Nikitax23 commented on Movies/Movies/CoreData/MovieEntity+CoreDataClass.swift
> +                return fetchResult[0]
этим должен заниматься кор дата сервис

2022-10-07 17:09 UTC, Nikitax23 commented on Movies/Movies/CoreData/MovieEntity+CoreDataProperties.swift
> +    @NSManaged public var poster: Data?
я бы сказал, что лучше хранить урл на постер. 
и по урл доставать его из места, где он сохранен (если реализовано так, что он куда-то сохраняется)

2022-10-07 17:09 UTC, Nikitax23 commented on Movies/Movies/Extensions/String+Extension.swift
> +    static func getYear(stringDate: String) -> String {
это как бы не совсем правильно. 
это должно находиться в `extension Date` .

И `DateFormatter` должен быть один , статический, уже настроенный.

2022-10-07 17:09 UTC, Nikitax23 commented on Movies/Movies/Extensions/UICollectionViewCell+Extension.swift
> +        layer.borderWidth = 1.0
непонятно, почему ты это делаешь в екстеншне UICollectionViewCell. 

1) почему не UIView? 
2) почему в методе хардово прописаны все значения, и он не принимает никаких параметров? 
3) почему тут и бордер, и тень описывается, и всё остальное?

2022-10-07 17:09 UTC, Nikitax23 commented on Movies/Movies/Extensions/UIImageView+Extension.swift
> +                  endPoint: EndPoint,
у тебя этот екстеншн не универсальный. 
он зависит от EndPoint, он зависит от файла констант, он имеет такие слова, как "постер", а ничего не должен об этом знать. 
такой екстеншн должен быть абстрактным, максимально

2022-10-07 17:09 UTC, Nikitax23 commented on Movies/Movies/Modules/Details/DefaultDetailsAssembly.swift
> +    func createTrailerModule(trailerID: String) -> YouTubePlayerViewController {
тут же ничего не ассемблится) это должно быть в роутере))

2022-10-07 17:09 UTC, Nikitax23 commented on Movies/Movies/Modules/Details/Model/Details.swift
> +        self.genres = try container.decodeIfPresent([Genre].self, forKey: .genres) ?? []
хороший поинт , как избежать ошибки парсинга всей модели, когда пришло "не так", или не пришло какое-то поле. 

но тут уж надо или везде это использовать (кастомный декодинг), либо оставлять опционалы там, где это не обрабатывается

2022-10-07 17:09 UTC, Nikitax23 commented on Movies/Movies/Modules/Details/DetailsNetworkManager.swift
> +    func fetchDetails(movieID: Int, completion: @escaping DetailsBlock) {
это не совсем правильно. 

Это как сервис, который владеет нетворк сервисом, как инстансом. а не реализовывает протокол и наследуется от нетворк сервиса.

то есть, тут должно быть свойство `networkService` , которое и будет выполять риквесты. 
При чем это свойство должно быть типа протокола NetworkService. и ты должен принимать его на ините . 
Можно в ините даже сделать так `init(networkService: NetworkService = DefaultNetworkService()) {}`. 

Ну и название можно поменять. `DetailsNetworkManager ` => `MovieDetailsRepository` / `MovieDetailsService`

2022-10-07 17:09 UTC, Nikitax23 commented on Movies/Movies/Modules/Details/Presenter/DetailsViewPresenter.swift
> +                group.enter()
здесь в этой диспатч группе нет никакого смысла. 
Ты вызываешь `self.networkManager.fetchTrailerID` внутри комплишн блока метода `networkManager.fetchDetails` .

2022-10-07 17:09 UTC, Nikitax23 commented on Movies/Movies/Modules/Details/Presenter/DetailsViewPresenter.swift
> +    func playButtonTapped()
не нужно называть методы презентера так, чтоб там были названия UI элементов. 

Почему не назвать `showTrailer` , `openPoster` ? 
не привязывай никак презентер к UI

2022-10-07 17:09 UTC, Nikitax23 commented on Movies/Movies/Modules/Details/Presenter/DetailsViewPresenter.swift
> +    private func convertToModel(item: DetailsData) -> DetailModel {
это можно вынести в статическую функцию для `DetailModel`. 
например, `static func from(networkModel: DetailsData) -> DetailModel {...}`

2022-10-07 17:09 UTC, Nikitax23 commented on Movies/Movies/Modules/Details/View/DetailsViewController.swift
> +        countryLabel.text = movie.countries.joined(separator: ", ")
`", "`
у тебя повторяется использование этого. можно вынести в екстеншн, переиспользовать)

2022-10-07 17:09 UTC, Nikitax23 commented on Movies/Movies/Modules/Details/View/DetailsViewController.swift
> +        rankLabel.text = String(format: "%.1f", movie.voteAverage)
`rankLabel.text = String(format: "%.1f", movie.voteAverage)`

скорее всего ты это используешь и на списке) есть вариант переиспользовать это, вынеся в экстеншн

2022-10-07 17:09 UTC, Nikitax23 commented on Movies/Movies/Modules/Details/View/DetailsViewController.swift
> +        if movie.trailerID != nil {
```
 if movie.trailerID != nil {
            trailerButton.isHidden = false
        }
```

=> 

`trailerButton.isHidden = movie.trailerID == nil`

2022-10-07 17:09 UTC, Nikitax23 commented on Movies/Movies/Modules/Details/View/DetailsViewController.swift
> +        votesCountLabel.text = String(movie.voteCount)
`        votesCountLabel.text = String(movie.voteCount)
`

кастинг данных следует вынести в екстеншн. 
чтоб можно было вызывать `movie.voteCount.stringValue`

2022-10-07 17:09 UTC, Nikitax23 commented on Movies/Movies/Modules/Details/View/DetailsViewController.swift
> +        DispatchQueue.main.async {
в текущей реализации ты диспатч групп нотифай ввыполняешь на мейне) там же у тебя дёргается этот метод

2022-10-07 17:09 UTC, Nikitax23 commented on Movies/Movies/Modules/Movies/DefaultMoviesAssembly.swift
> +protocol PostListAssembly {
`PostListAssembly` 
кто-то забыл переименовать копипаст)

2022-10-07 17:09 UTC, Nikitax23 commented on Movies/Movies/Modules/Movies/Model/Movies.swift
> +        case voteCount = "vote_count"
то же самое с Codable

2022-10-07 17:09 UTC, Nikitax23 commented on Movies/Movies/Modules/Movies/MoviesNetworkManager.swift
> +        case .byPopularity:
думаю, это можно было не разделять на разные сетевые запросы! 
есть другой вариант) посмотри апи. 
есть сетевой запрос, в котором можно получать фильмы, и передать туда параметр сортировки

2022-10-07 17:09 UTC, Nikitax23 commented on Movies/Movies/Modules/Movies/View/CollectionViewCell.swift
> +        posterImageView.image = nil
```
 posterImageView.image = nil
        posterImageView.kf.cancelDownloadTask()
```

это лучше делать в configure

2022-10-07 17:09 UTC, Nikitax23 commented on Movies/Movies/Modules/Movies/View/CollectionViewCell.swift
> +        posterImageView.layer.cornerRadius = 10
`posterImageView.layer.cornerRadius`

почему опять layer.cornerRadius? есть же екстеншн

2022-10-07 17:09 UTC, Nikitax23 commented on Movies/Movies/Modules/Movies/View/CollectionViewCell.swift
> +        genresTotalLabel.text = movie.genres.joined(separator: ", ")
`", "`

опять используешь это

2022-10-07 17:09 UTC, Nikitax23 commented on Movies/Movies/Modules/Movies/Presenter/MoviesViewPresenter.swift
> +        timer = .scheduledTimer(withTimeInterval: 1.0, repeats: false) { _ in
здесь не нужно использовать таймер. 
здесь нужно использовать GCD. с DispatchWorkItem , с отменой, с задержкой.

2022-10-07 17:09 UTC, Nikitax23 commented on Movies/Movies/Modules/Movies/Presenter/MoviesViewPresenter.swift
> +                        .filter { $0.title.lowercased().contains(self.searchText.lowercased()) }
`.filter { $0.title.lowercased().contains(self.searchText.lowercased())`
зачем ты это здесь делаешь, если ты уже и так засёрчил и отфильтровал элементы, с помощью апи?

2022-10-07 17:09 UTC, Nikitax23 commented on Movies/Movies/Modules/Movies/Presenter/MoviesViewPresenter.swift
> +    private var pageCounter: Int = 1
`pageCounter`
лучше просто назвать это page

2022-10-07 17:09 UTC, Nikitax23 commented on Movies/Movies/Modules/Movies/Presenter/MoviesViewPresenter.swift
> +    private var searchIsActive: Bool = false
`searchIsActive`
это может быть прoсто computed Property, которая основывается на searchText-e и его пустоте)

2022-10-07 17:09 UTC, Nikitax23 commented on Movies/Movies/Modules/Movies/Presenter/MoviesViewPresenter.swift
> +        monitor.pathUpdateHandler = { path in
ты будешь каждый раз вызывать и прогонять этот метод, когда захочешь промониторить состояние сети? 

можно либо уйти от этого решение, так как оно по сути ничего не мониторит и не апдейтит. 
либо получать просто в ответ на сетевые от аламофаера ошибку "нетворк еррор" , обрабатывать её и тогда прокидывать на слой выше, и в по итогу в юай

2022-10-07 17:09 UTC, Nikitax23 commented on Movies/Movies/Modules/Movies/Presenter/MoviesViewPresenter.swift
> +        let movie = MovieModel(genres: genres,
то же самое с этой моделью, я уже приводил пример с деталями

2022-10-07 17:09 UTC, Nikitax23 commented on Movies/Movies/Modules/Movies/Presenter/MoviesViewPresenter.swift
> +        let releaseYear: String = .getYear(stringDate: item.releaseDate)
тут неправильное. использование.  в екстеншне прокомментировал.

2022-10-07 17:09 UTC, Nikitax23 commented on Movies/Movies/Modules/Movies/Presenter/MoviesViewPresenter.swift
> +    func modelIsReadyToSave(movie: MovieModel, poster: UIImage?) {
`modelIsReadyToSave`

почему название этого метода читается, как булевая переменная?

2022-10-07 17:09 UTC, Nikitax23 commented on Movies/Movies/Modules/Movies/Presenter/MoviesViewPresenter.swift
> +            searchIsActive ?
`searchIsActive`
правильно назвать эту переменную `isSearchActive`

2022-10-07 17:09 UTC, Nikitax23 commented on Movies/Movies/Modules/Movies/Presenter/MoviesViewPresenter.swift
> +        if searchIsActive {
можно чтоб везде не делать эту проверку, сделать один раз 

```
var list: [MovieModel] {
return isSearchActive ? searchResults : movies
}
```

2022-10-07 17:09 UTC, Nikitax23 commented on Movies/Movies/Modules/Movies/Presenter/MoviesViewPresenter.swift
> +                    self.movies = movies
эмм)) то есть когда мы будем получать результаты последней страницы, то та затрёшь все старые результаты (1000 штук) и заместишь их новыми (10 шт), и останется 10 штук, вместо 1010 штук???

2022-10-07 17:09 UTC, Nikitax23 commented on Movies/Movies/Modules/Movies/Presenter/MoviesViewPresenter.swift
> +        let filtred = self.movies.filter { $0.title.lowercased().contains(self.searchText.lowercased()) }
`filtred` опечатка

2022-10-07 17:09 UTC, Nikitax23 commented on Movies/Movies/Modules/Movies/Presenter/MoviesViewPresenter.swift
> +        let filtred = self.movies.filter { $0.title.lowercased().contains(self.searchText.lowercased()) }
`filtred` можно не создавать промежуточную переменную

2022-10-07 17:09 UTC, Nikitax23 commented on Movies/Movies/Modules/Movies/View/MoviesViewController.swift
> +        if searchText.count >= minSymbolsToSearch {
никакой логики не должно быть в контроллере

2022-10-07 17:09 UTC, Nikitax23 commented on Movies/Movies/Modules/Movies/View/MoviesViewController.swift
> +        DispatchQueue.main.async {
зачем здесь   DispatchQueue.main.async {} ? почему сам метод не вызвать в этой обёртке, в презентере?

2022-10-07 17:09 UTC, Nikitax23 commented on Movies/Movies/Modules/Movies/View/MoviesViewController.swift
> +        DispatchQueue.main.async {
то же самое здесь

2022-10-07 17:09 UTC, Nikitax23 commented on Movies/Movies/Modules/Movies/View/MoviesViewController.swift
> +        DispatchQueue.main.async {
то же самое здесь

2022-10-07 17:09 UTC, Nikitax23 commented on Movies/Movies/Modules/Movies/View/MoviesViewController.swift
> +            guard let self = self else { return }
зачем ты здесь лишний раз разворачиваешь self? 
если здесь даже не на что это не влияет
просто вызвал бы себе `self?.presenter`. ...

2022-10-07 17:09 UTC, Nikitax23 commented on Movies/Movies/Modules/Movies/View/MoviesViewController.swift
> +        collectionView.setContentOffset(.zero, animated: false)
`collectionView.scrollToItemAtIndexPath(...)`

2022-10-07 17:09 UTC, Nikitax23 commented on Movies/Movies/Modules/Movies/Presenter/MoviesViewPresenter.swift
> +        networkManager.fetch(page: pageCounter, sortType: sortType) { [weak self] result in
не обрабатывается isLoading у тебя. 
запросы могут накладываться при пагинации

2022-10-07 17:09 UTC, Nikitax23 commented on Movies/Movies/Modules/Movies/Presenter/MoviesViewPresenter.swift
> +        getGenres()
тебе нужно работать с уже готовыми жанрами, когда ты получаешь фильмы. значит нужно выполить эти запросы последовательно.

2022-10-07 17:09 UTC, Nikitax23 commented on Movies/Movies/Modules/Movies/Presenter/MoviesViewPresenter.swift
> +        pageCounter += 1
`+= 1`

можно вынести в екстеншн инта, как `increment()` метод

2022-10-07 17:09 UTC, Nikitax23 commented on Movies/Movies/Modules/Movies/Presenter/MoviesViewPresenter.swift
> +    func modelIsReadyToSave(movie: MovieModel, poster: UIImage?)
`modelIsReadyToSave` 

1) очень плохое название
2) заччем оно тебе где-либо из-вне??? это не должно выходить на уровень вью контроллера вообще!

2022-10-07 17:09 UTC, Nikitax23 commented on Movies/Movies/Modules/Poster/View/PosterViewController.swift
> +        self.posterImageView.setImage(size: .full, endPoint: .poster(path: path))
у тебя же уже есть эта картинка. Зачем еще раз её запрашивать и отображать?

2022-10-17 12:26 UTC, Ievgen-Mykhailiuk commented on Movies/Movies/Modules/Poster/View/PosterViewController.swift
> +        self.posterImageView.setImage(size: .full, endPoint: .poster(path: path))
У меня для постера который зумится отдельный запрос для большого разрешения.

2022-10-17 16:20 UTC, Ievgen-Mykhailiuk commented on Movies/Movies/Modules/Movies/Presenter/MoviesViewPresenter.swift
> +        monitor.pathUpdateHandler = { path in
Разобрался с нетворк монитором, оказывается он может некорректно работать на симуляторе, что и сбивало с толку, на девайсе все работает и мониторит в реальном времени. Добавил проверки что бы нотификация срабатывала только при смене статуса(он бывает апдейтит один и тот же статус несколько раз перед сменой)

2022-10-19 10:07 UTC, Ievgen-Mykhailiuk commented on Movies/Movies/Modules/Details/DetailsNetworkManager.swift
> +    func fetchDetails(movieID: Int, completion: @escaping DetailsBlock) {
Если я правильно понял задумку то MovieDetailsRepository класс по работе с данными. В моем случае данные могу быть как с сети так и с памяти, поэтому я решил сюда добавить и нетворк менеджер и кордата менеджер(хоть он у меня синглтон). И в презентере будет просто дата менеджер. Норм?

2022-10-19 15:46 UTC, Nikitax23 requested changes
есть моменты, которые следует улучшить

2022-10-19 15:46 UTC, Nikitax23 commented on Movies/Movies/Application/AppDelegate.swift
> +final class AppDelegate: UIResponder, UIApplicationDelegate {
не думаю, что стоит менять системный класс) но ладно

2022-10-19 15:46 UTC, Nikitax23 commented on Movies/Movies/Application/SceneDelegate.swift
> +final class SceneDelegate: UIResponder, UIWindowSceneDelegate {
то же самое

2022-10-19 15:46 UTC, Nikitax23 commented on Movies/Movies/CoreData/MovieEntity+CoreDataProperties.swift
> +    @NSManaged public var overview: String
а где урл картинки?

2022-10-19 15:46 UTC, Nikitax23 commented on Movies/Movies/Extensions/Int+Extension.swift
> +    var value: Int {
а какой смысл в этом? 
если для increment функции, то ты можешь просто делать `self += 1 `

2022-10-19 15:46 UTC, Nikitax23 commented on Movies/Movies/Extensions/UIImageView+Extension.swift
> +            completion?()
можно так, а можно комплишн передать

2022-10-19 15:46 UTC, Nikitax23 commented on Movies/Movies/Extensions/UIView+Extension.swift
> +                   offset: CGSize = CGSize(width: 4.0, height: 3.0),
а зачем передавать опциональный цвет и если его нет, то ничего не делать? не вижу смысла

2022-10-19 15:46 UTC, Nikitax23 commented on Movies/Movies/Modules/Details/View/DetailsViewController.swift
> +        setupNavigationBar(title: movie?.title ?? .empty)
навигейшн бар можно сетапить и во вью дид лоаде . у тебя есть название фильма еще с прошлого экрана) 

но не критично

2022-10-19 15:46 UTC, Nikitax23 commented on Movies/Movies/Modules/Movies/DefaultMoviesRepository.swift
> +    }
смотри
я бы сказал, что в данном случае кор дату выносить на слой выше и не нужно. 

для этого тебе репозиторий и нужен. 
не для того, чтоб ты в нём тупо повызывал другие сервисы и вернул ответ в том же виде, а для того, чтоб это здесь похендлить внутри. 
то есть 1) fetch должен выполниться или из кор даты , или из нетворк сервиса
2) saveToDatabase должен произойти сам по себе, внутри репозитория. когда ты получил результаты)

2022-10-19 15:46 UTC, Nikitax23 commented on Movies/Movies/Modules/Movies/Presenter/MoviesViewPresenter.swift
> +        let newSearchWorkItem = DispatchWorkItem {
смотри, это отменяет будущие операции, которые могли "встать в очередь", за счет задержки. 
но не отменяет предудыщего запроса. 
его тоже можно отменять, используя метод cancel в сетевом слое. 
можешь спросить у коллеги) он сделал

2022-10-19 15:46 UTC, Nikitax23 commented on Movies/Movies/Modules/Movies/Presenter/MoviesViewPresenter.swift
> +        if isLoading {
не принципиально, но лучше guard !isLoading else { return }

2022-10-19 15:46 UTC, Nikitax23 commented on Movies/Movies/Modules/Movies/Presenter/MoviesViewPresenter.swift
> +            isNetworkAvailable = true
а смысл?)))
смысл хранить такую переменную, если можно обращаться к `ReachabilityManager`?

2022-10-19 15:46 UTC, Nikitax23 commented on Movies/Movies/Modules/Movies/Presenter/MoviesViewPresenter.swift
> +        ReachabilityManager.shared.start()
ричабилити менеджер старт должен происходить на старте приложения. 
а вот обзёрвить его надо здесь, да

2022-10-19 15:46 UTC, Nikitax23 commented on Movies/Movies/Modules/Movies/Presenter/MoviesViewPresenter.swift
> +        ReachabilityManager.shared.start()
и не забывать удалять обзёрвер, когда презентер деинитится

2022-10-19 15:46 UTC, Nikitax23 commented on Movies/Movies/Modules/Movies/Presenter/MoviesViewPresenter.swift
> +        movies = []
можно делать movies.removeAll()

2022-10-19 15:46 UTC, Nikitax23 commented on Movies/Movies/Modules/Movies/View/CollectionViewCell.swift
> +    @IBOutlet weak var shadowView: UIView!
private

2022-10-19 15:46 UTC, Nikitax23 commented on Movies/Movies/Modules/Movies/View/CollectionViewCell.swift
> +        shadowView.cornerRadius = radius
не обязательно чтоб задать тень, создавать для этого отдельную вью. 
можно текущему контейнеру задать тень

2022-10-19 15:46 UTC, Nikitax23 commented on Movies/Movies/Modules/Movies/View/MoviesViewController.swift
> +            presenter.getSortedMovies(currentSortType)
скролл лучше делать по результату выполнения `getSortedMovies` . 
во вью протокол методе

2022-10-19 15:46 UTC, Nikitax23 commented on Movies/Movies/Modules/Movies/View/MoviesViewController.swift
> +        let tap = UITapGestureRecognizer(target: self, action: #selector(scrollToTopButtonTapped(_:)))
не уверен, что есть смысл в этой кнопке) 
ты можешь нажать на системный статус бар и получишь тот же самый результат) попробуй

2022-10-19 15:46 UTC, Nikitax23 commented on Movies/Movies/Modules/Poster/Presenter/PosterViewPresenter.swift
> +    func swiped()
опять эта ошибка) 
сделай метод close, а не swiped. 
презентер не знает, по какому жесту надо закрыться) он знает, что надо закрыться и всё

2022-10-19 15:46 UTC, Nikitax23 commented on Movies/Movies/Services/NetworkService/EndPoint.swift
> +            return "/\(apiVersion)/genre/movie/list"
вот смотри) ты везде 10000 раз вставляешь `apiVersion` . 
это же можно сделать в одном месте, когда складываешь урл, верно?

2022-10-19 15:46 UTC, Nikitax23 commented on Movies/Movies/Services/ReachabilityManager.swift
> +        let reachability = note.object as! Reachability
я бы тут switch -ом прошелся. и в зависимости от него отправлял или не отправлял нотификацию. 
смысл хранить лишнюю переменную ?

2022-10-19 15:46 UTC, Nikitax23 commented on Movies/Movies/Services/ReachabilityManager.swift
> +            try reachability?.startNotifier()
не вижу смысла в таком do {} catch {}. если ты его не обрабатываешь

тогда можно просто 

`try? reachability?.startNotifier()`

2022-10-19 15:46 UTC, Nikitax23 commented on Movies/Movies/Services/ReachabilityManager.swift
> +        stopNotifier()
зачем тут делать стоп, а потом старт? думаю , это лишнее.
если есть аргументы, то напишешь

2022-10-19 15:46 UTC, Nikitax23 commented on Movies/Movies/Utilities/NetworkError.swift
> +    var localizedDescription: String {
ну такое) 
название `localizedDescription`, а твоя строка по факту не локализована) 
назови просто `errorDescription` или что-то типа того

2022-10-21 12:32 UTC, Ievgen-Mykhailiuk commented on Movies/Movies/CoreData/MovieEntity+CoreDataProperties.swift
> +    @NSManaged public var overview: String
У меня хранится путь на картинку. А урл я конфигурирую взависимости от нужного мне размера, потому что он отличается. w300 или original. Я ж в целях экономии ресурсов так сделал. Имэдж менеджер все равно ж сохраняет в кеш по урл. Или я неправильно понял?

2022-10-24 09:57 UTC, Ievgen-Mykhailiuk commented on Movies/Movies/Modules/Movies/Presenter/MoviesViewPresenter.swift
> +        ReachabilityManager.shared.start()
Написано в документации:

If your app targets iOS 9.0 and later or macOS 10.11 and later, and you used [addObserver(_:selector:name:object:)](https://developer.apple.com/documentation/foundation/notificationcenter/1415360-addobserver), you do not need to unregister the observer. If you forget or are unable to remove the observer, the system cleans up the next time it would have posted to it.

2022-10-24 10:21 UTC, Ievgen-Mykhailiuk commented on Movies/Movies/Services/ReachabilityManager.swift
> +        stopNotifier()
Так тут прописана логика этой либы(я ее взял с гитхаба  этой либы). Она основывается на повторяющихся запросах.  Если сделать что бы она работала в режиме реального времени она так же некорректно отображает статусы как у меня было с NWPathMonitor (например при потере  соеденения с интернетом она может выдать статус что интернет есть или вообще никак не отреагировать).  Конечно я не исключаю вероятность что я чего-то не догоняю))))) Но работает корректно(проверял)

2022-10-24 10:29 UTC, Ievgen-Mykhailiuk commented on Movies/Movies/Services/ReachabilityManager.swift
> +        let reachability = note.object as! Reachability
Тут у меня логика такая: нотификация срабатывает ТОЛЬКО при смене статуса. А презентер уже обрабатывает эту смену(если соеденение потеряно то пропадает с экрана сортировка, появляется алерт и подгружается все из кордаты)

2022-10-24 11:50 UTC, Ievgen-Mykhailiuk commented on Movies/Movies/Modules/Details/View/DetailsViewController.swift
> +        setupNavigationBar(title: movie?.title ?? .empty)
Блин я сначала игрался с юай и решил сделать текст с атрибутами в навбаре. А только потом дошел до этого коммента и начал пробовать и понял что походу на этапе загрузки можно присвоить тайтл, но как-то настроить его атрибутами нельзя.

2022-10-24 15:41 UTC, Nikitax23 requested changes
Есть моменты к оптимизации.
 
Уже лучше! 

**!Важно!** 
Везде, где у тебя есть синглтоны - нужно обязательно создавать `private init() {}` . 
Это делается для того, чтоб невозможно было проинициализировать инстанс этого класса дополнительно.

2022-10-24 15:41 UTC, Nikitax23 commented on Movies/Movies/Modules/Movies/DefaultMoviesAssembly.swift
> +        ]
```
navigationController.navigationBar.tintColor = Constants.appShadowColor
        navigationController.navigationBar.titleTextAttributes = [
            .font: UIFont(name: Constants.appFont, size: 30) as Any,
            .foregroundColor: Constants.appShadowColor as Any
        ]
```

все настройки навигейшн бара должны быть во `viewDidLoad` , в классе вью контроллера!

2022-10-24 15:41 UTC, Nikitax23 commented on Movies/Movies/Modules/Movies/DefaultMoviesRepository.swift
> +                    for movie in movies {
может есть смысл сделать метод у кор дата сервиса , который принимает массив и сохраняет массив? 

если так оставить, то так ты в каждом месте, где тебе надо сохранить список - будешь писать цикл

2022-10-24 15:41 UTC, Nikitax23 commented on Movies/Movies/Modules/Movies/Model/Movies.swift
> +            let movie = MovieModel(genres: genres,
рекомендую создать методы для вот этих вещей с трансформацией из одной модели в другую. 
У тебя есть UI модель. Вот создай в ней два статических метода `static func from(_ networkModel/storedModel) -> UIModel`

2022-10-24 15:41 UTC, Nikitax23 commented on Movies/Movies/Modules/Movies/Model/Movies.swift
> +            let movie = MovieModel(genres: genres,
чтоб ты тут просто мог вызвать `= .from(...)`

2022-10-24 15:41 UTC, Nikitax23 commented on Movies/Movies/Modules/Movies/Presenter/MoviesViewPresenter.swift
> +        NotificationCenter.default.removeObserver(self, name: .networkStatusChanged, object: nil)
некритично, но я бы вынес это в метод `removeNetworkStateObserver`

2022-10-24 15:41 UTC, Nikitax23 commented on Movies/Movies/Modules/Movies/Presenter/MoviesViewPresenter.swift
> +            if nextPage {
1) `nextPage` плохое название переменной. интуитивно nextPage - это инт ))) но никак не бул. сделай `hasNextPage`

2) тут можно обойтись одним `guard` .

`guard hasNextPage, let currentPage = self.list.last?.page, ...` и тд

2022-10-24 15:41 UTC, Nikitax23 commented on Movies/Movies/Modules/Movies/Presenter/MoviesViewPresenter.swift
> +            if let currentPage = self.list.last?.page, let totalPages = self.list.last?.totalPages, currentPage < totalPages {
то же самое здесь

2022-10-24 15:41 UTC, Nikitax23 commented on Movies/Movies/Modules/Movies/Presenter/MoviesViewPresenter.swift
> +    func itemSelected(at index: Int) {
`itemSelected` -> `didSelectItem`

2022-10-24 15:41 UTC, Nikitax23 commented on Movies/Movies/Modules/Movies/View/MoviesViewController.swift
> +        navigationItem.setRightBarButton(sortButton, animated: false) :
лучше не так сделать. 

ты два раза опять пишешь одно и то же! 
старайся следовать принципу `DRY ` https://habr.com/ru/post/144611/

`navigationItem.setRightBarButton(isAvailable ? sortButton : nil, animated: false) `

2022-10-25 10:52 UTC, Ievgen-Mykhailiuk commented on Movies/Movies/Modules/Movies/Model/Movies.swift
> +            let movie = MovieModel(genres: genres,
Я сделал как понял. Но как-то мне и самому не очень нравится(   У меня логика такая что я сохраняю в модель currentPage totalPages и это оказалось удобно в презентере для пагинации. Но в разрезе вопроса трансформации networkModel -> UIModel окончательная модель для UI теперь сетится за два раза.  Одна часть из Response(page, totalPages) вторая из response.results(все остальное) Так вообще практикуют? не знаю как красиво сделать

2022-10-25 11:36 UTC, Ievgen-Mykhailiuk commented on Movies/Movies/Modules/Movies/Presenter/MoviesViewPresenter.swift
> +            if nextPage {
Не получается мне так сделать. hasNextPage мне приходит параметром и если он false то var page = 1 так и остается и в hasNextPage не попадаем, если true то внутри еще проверка на последнюю страницу где я уже могу применить ранний выход с помощью guard если страница последняя или сделать .increment() если нет

2022-10-25 12:08 UTC, Ievgen-Mykhailiuk commented on Movies/Movies/Modules/Movies/View/MoviesViewController.swift
> +        navigationItem.setRightBarButton(sortButton, animated: false) :
спасибо, возьму на заметку!

2022-10-27 07:31 UTC, Nikitax23 commented on Movies/Movies/Modules/Movies/DefaultMoviesRepository.swift
> +    private func moviesFrom(_ data: MovieResponse, using genres: [GenreModel]) -> [MovieModel] {
`private func moviesFrom(_ data: MovieResponse, using genres: [GenreModel])`

плохое название. не по гайдлайнам.

если уже и хочешь так назвать, то хотя бы вот так 
`private func prepareMovieList(from response: MovieResponse, by genres: genres: [GenreModel])`

2022-10-27 07:49 UTC, Nikitax23 requested changes
Есть моменты к улучшению) осталось немножко

2022-10-27 07:49 UTC, Nikitax23 commented on Movies/Movies/Modules/Movies/Presenter/MoviesViewPresenter.swift
> +            ReachabilityManager.shared.isNetworkAvailable ?
это вообще стоит перенести в репозиторий) 
логика же та же самая. 
говоришь репозиторию "сёрч", а он уже сам решает, откуда сёрчить

2022-10-27 07:49 UTC, Nikitax23 commented on Movies/Movies/Modules/Movies/Presenter/MoviesViewPresenter.swift
> +        if isNextPageNeeded {
`isNextPageNeeded`
назови пожалуйста  `hasNextPage` )))

2022-10-28 07:39 UTC, Nikitax23 commented on Movies/Movies/Utilities/SearchAttribute.swift
> +    var predicate: NSPredicate {
да, хорошая идея. только сделай предикат опциональным. 
так будет более универсально.

2022-10-28 07:41 UTC, Nikitax23 commented on Movies/Movies/CoreData/MovieEntity+CoreDataClass.swift
> +    class func find(in attribute: SearchAttribute, context: NSManagedObjectContext) throws -> [MovieEntity]? {
можно ещё попробовать сделать это протоколом и на дженериках ) 
не обязательно, но попробовать можно.

2022-10-28 07:41 UTC, Nikitax23 approved these changes
Есть пару моментов, куда можно посмотреть, но это больше в плане общего развития. 
В целом - молодец !

2022-10-31 10:54 UTC, Nikitax23 commented on Movies/Movies/CoreData/MovieEntity+CoreDataClass.swift
> +protocol EntityType: NSManagedObject {
всё хорошо, только не понятно, почему название `EntityType`?  звучит, как какой-то `enum`

2022-10-31 10:57 UTC, Nikitax23 commented on Movies/Movies/CoreData/MovieEntity+CoreDataClass.swift
> +protocol EntityType: NSManagedObject {
и зачем здесь `protocol EntityType: NSManagedObject` это `NSManagedObject` ? если ты потом его добавляешь всё равно в каждой энтити?

2022-10-31 11:01 UTC, Nikitax23 requested changes

2022-10-31 11:01 UTC, Nikitax23 commented on Movies/Movies/CoreData/MovieEntity+CoreDataClass.swift
> +public class MovieEntity: NSManagedObject, EntityType {
`public class MovieEntity`
здесь думаю можно `public final class` . вряд ли ты будешь наследоваться еще от него

2022-10-31 11:01 UTC, Nikitax23 commented on Movies/Movies/CoreData/MovieEntity+CoreDataProperties.swift
> +extension MovieEntity: Identifiable {
зачем ты здесь добавляешь соответствие `Identifiable` протоколу, если у тебя EntityType и так обязывает добавить свойство `identifier` ?

2022-10-31 11:01 UTC, Nikitax23 commented on Movies/Movies/CoreData/MovieEntity+CoreDataProperties.swift
> +extension MovieEntity: Identifiable {
а здесь по итогу остается пустой екстеншн

2022-10-31 11:01 UTC, Nikitax23 commented on Movies/Movies/Services/DefaultCoreDataService.swift
> +    func all<T: EntityType>(completion: @escaping (Result<[T], Error>) -> Void)
`all`
мне не нравится это название. 
что all?) 
`fetchAll ` - подтянуть/получить все, `getAll` - получить все , `all` - все )) ну такое...

2022-10-31 11:01 UTC, Nikitax23 commented on Movies/Movies/Modules/Movies/DefaultMoviesRepository.swift
> +            coreDataService.all { (result: Result<[MovieEntity], Error>) in
следует поменять название метода coreDataService.all

2022-11-01 08:49 UTC, Nikitax23 commented on Movies/Movies/Utilities/BaseEntity.swift
> +protocol Fetchable: NSManagedObject {
здесь не нужно `NSManagedObject` . 
Не знаю, почему у тебя не собирается, у меня - ок.

2022-11-01 08:49 UTC, Nikitax23 approved these changes
молодец! жду сборку!

2022-11-14 12:10 UTC, merged